version: '3.8'
services:
  dust3r-demo:
    build:
      context: .
      dockerfile: cuda.Dockerfile 
    environment:
      - DEVICE=cuda
      - MODEL=${MODEL:-DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth}
    volumes:
      - ./dust3r:/dust3r/
      - ./code:/code/
      - ../../datasets/:/datasets/
    cap_add:
      - IPC_LOCK
      - SYS_RESOURCE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
